---
deployment:
  tasks:
    #- export DEPLOYPATH=/home/u4396178/irtvhn.info/mk/
    - export DEPLOYPATH=/home/u5233116/web/mk/
    - /bin/cp -R * $DEPLOYPATH
    #- /bin/rsync -a --exclude 'conn.php' public/ $DEPLOYPATH
