---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u4396178/irtvhn.info/mk/
    #- export DEPLOYPATH=/home/megaaxmg/teombley.asia/iraffle/mk/
    - /bin/cp -R * $DEPLOYPATH
    #- /bin/rsync -a --exclude 'conn.php' public/ $DEPLOYPATH
